Djangogirls csv
pyconau2017/website pull request #73
Opened 2017-06-26 04:29 UTC by clintonroy

2017-07-04 23:57 UTC, r1chardj0n3s requested changes

2017-07-04 23:57 UTC, r1chardj0n3s commented on pinaxcon/registrasion/management/commands/djangogirls.py
> +                    ticket_purchased = True
Just in case - shouldn't we check to see whether they've got *any* sort of ticket?

2017-07-04 23:57 UTC, r1chardj0n3s commented on pinaxcon/registrasion/models.py
> +    def save(self, force_insert=False, force_update=False, using=None):
If the args are ignored, I'd just **kw them. Whatever tho, I guess.

2017-07-04 23:58 UTC, clintonroy commented on pinaxcon/registrasion/models.py
> +    def save(self, force_insert=False, force_update=False, using=None):
So. this particular change is required in order for the generic object.save() thing to work.

2017-07-04 23:59 UTC, clintonroy commented on pinaxcon/registrasion/management/commands/djangogirls.py
> +                    ticket_purchased = True
Possibly? My feeling is that we want all the django girls attendees to have a djangogirls ticket. they may well have a student ticket or whatever, in which case they get two badges or whatever.

2017-07-05 00:03 UTC, r1chardj0n3s commented on pinaxcon/registrasion/models.py
> +    def save(self, force_insert=False, force_update=False, using=None):
OK.

2017-07-05 00:03 UTC, r1chardj0n3s commented on pinaxcon/registrasion/management/commands/djangogirls.py
> +                    ticket_purchased = True
If they use the same email for an existing ticket then the above will give them two invoiced registration tickets, which surely will confuse things...

2017-07-05 00:05 UTC, clintonroy commented on pinaxcon/registrasion/management/commands/djangogirls.py
> +                    ticket_purchased = True
I think that's exactly what's needed though? As the djangogirls event is considered separate? I'm happy either way.

2017-07-05 00:07 UTC, r1chardj0n3s commented on pinaxcon/registrasion/management/commands/djangogirls.py
> +                    ticket_purchased = True
It's not a separate event though - the djangogirls attendees can add a Sunday to their ticket (or sprints, or Friday). It's just that their attendance on Saturday *is most likely* going to be free. But if they do already have a ticket that includes Saturday for whatever reason, they don't need the additional djangogirls freebie ticket...

2017-07-11 07:17 UTC, merged